name: sound_table_teniss_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #speech_to_text
  flutter_tts: ^3.3.3
  #getX
  get: ^4.6.1
  #flip card
  flip_card: ^0.6.0
  #four direction swipe
  four_swipe_direction: ^0.0.4
  #gif splash screen
  animated_splash_screen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.gif

